// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EndLocationAutocompleteController from "./end_location_autocomplete_controller"
application.register("end-location-autocomplete", EndLocationAutocompleteController)


import StartLocationAutocompleteController from "./start_location_autocomplete_controller"
application.register("start-location-autocomplete", StartLocationAutocompleteController)


import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import { Application } from "stimulus"
import Carousel from "stimulus-carousel"

const application = Application.start()
application.register("carousel", Carousel)
